sudo: true

language: cpp

# Build with gcc and clang.
compiler:
  - gcc
  - clang

# Build both debug and release configurations, through use of an environment variable in the build matrix.
env:
  - CONFIGURATION=debug
  - CONFIGURATION=release

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq libyajl-dev libxml2-dev libxqilla-dev
  - if [ "$CC" = "gcc" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CC" = "gcc" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - if [ "$CC" = "clang" ]; then sudo apt-get install -qq libstdc++-4.8-dev; fi

install:
  # Download and build SDL2 from source.
  - mkdir dummyprefix
  - export PREFIX=$PWD/dummyprefix
  - export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig
  - export PATH=$PATH:$PWD/dummyprefix/bin
  - wget https://www.libsdl.org/release/SDL2-2.0.4.tar.gz -O SDL2.tar.gz
  - tar -xzf SDL2.tar.gz
  - cd SDL2-2.0.4
  - ./configure --prefix=$PREFIX
  - make -j5
  - make install
  - cd ..
  # Download and build premake5 from source; the Travis environment doesn't have the right version of glibc6 for the prebuilt binaries to work.
  - wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha6/premake-5.0.0-alpha6-src.zip -O premake.zip
  - unzip premake.zip
  - cd premake-5.0.0-alpha6/build/gmake.unix
  - make config=release
  - cd ../../..
  - mv premake-5.0.0-alpha6/bin/release/premake5 premake5

# Run premake to generate makefiles.
# Have to cd into directory and back out since premake5 doesn't appear to accept a directory argument.
before_script:
  - cd RecastDemo && ../premake5 gmake && cd ..

# Run make in the directory containing generated makefiles, on the configuration specified by the environment variable.
script:
  - if [ "$CC" == "gcc-4.8" ]; then export CXXFLAGS="-std=c++1y"; fi
  - if [ "$CC" == "clang" ]; then export CXXFLAGS="-std=c++1y -stdlib=libc++"; fi
  - echo $CC
  - echo $CXX
  - echo $CXXFLAGS
  - make -C RecastDemo/Build/gmake config=$CONFIGURATION
  - RecastDemo/Bin/Tests
